# Generated by Django 5.0.3 on 2024-04-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RatePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_type", models.CharField(blank=True, max_length=20, null=True)),
                ("lv1d", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv1t", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv1f", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv1s", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv2d", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv2t", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv2f", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv2s", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv3d", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv3t", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv3f", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv3s", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv4d", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv4t", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv4f", models.DecimalField(decimal_places=0, max_digits=10)),
                ("lv4s", models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
