# Generated by Django 5.0.3 on 2024-04-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("integration_status", models.BooleanField(default=False)),
                ("integration_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
