# Generated by Django 5.0.3 on 2024-04-04 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_channel"),
        ("pms", "0012_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="CMSReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_reservation_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "pms_reservation_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("pms_status", models.CharField(blank=True, max_length=20, null=True)),
                ("cms_status", models.CharField(blank=True, max_length=20, null=True)),
                ("actual_check_out_date", models.DateField(blank=True, null=True)),
                ("transmission_result", models.BooleanField(default=False)),
                (
                    "reservation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cms_reservations",
                        to="pms.reservation",
                    ),
                ),
            ],
        ),
    ]
