# Generated by Django 5.0.3 on 2024-04-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0006_history_user_ip"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("link_title", models.CharField(blank=True, max_length=20, null=True)),
                ("link", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
