# Generated by Django 5.0.3 on 2024-04-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0007_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="average_revenue_per_customer",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="channel",
            name="cancellation",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="length_of_stay",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="no_show",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="number_of_guests",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="reservation_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="revenue",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
