# Generated by Django 5.0.3 on 2024-04-03 01:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("group_id", models.CharField(blank=True, max_length=20, null=True)),
                ("guest_name", models.CharField(blank=True, max_length=30, null=True)),
                ("check_in_date", models.DateField(blank=True, null=True)),
                ("check_out_date", models.DateField(blank=True, null=True)),
                (
                    "length_of_stay",
                    models.IntegerField(blank=True, max_length=10, null=True),
                ),
                ("services", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_room_charge",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("vendor_name", models.CharField(blank=True, max_length=30, null=True)),
                ("rate_type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "market_segment",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "reservation_source",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("package", models.CharField(blank=True, max_length=20, null=True)),
                ("nationality", models.CharField(blank=True, max_length=20, null=True)),
                ("taxes", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "special_services",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "folio_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="reservation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room",
                to="pms.reservation",
            ),
        ),
    ]
