# Generated by Django 5.0.3 on 2024-04-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0004_remove_room_reservation_reservation_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="room",
        ),
        migrations.AddField(
            model_name="reservation",
            name="room_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="room_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="room_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
