# Generated by Django 5.0.3 on 2024-04-03 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0010_reservation_booker_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="room",
        ),
        migrations.AddField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="pms.room",
            ),
        ),
    ]
