# Generated by Django 5.0.3 on 2024-04-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0011_remove_reservation_room_reservation_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_number", models.CharField(blank=True, max_length=10, null=True)),
                ("task_name", models.CharField(blank=True, max_length=20, null=True)),
                ("task_status", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
